### ISSUE TITLE
Icon Reverts on App Update

### ISSUE THREAD

**Issue by dsully** [BoltAI/BoltAI#114]
Just as the title says. 

I have a different than default icon selected. Whenever there is an update, the default is set instead of my selection.

**Comment by longseespace** [comment]
Sorry for the issue. Due to a potential trademark issue, I have to revert back to the original icon a couple of times the last few releases. Will fix this today.

**Comment by longseespace** [comment]
I've fixed this in `v1.16.7`. Please update.

**Comment by dsully** [comment]
Looks good, thanks!

**Comment by edigaryev** [comment]
I think this is still happening on v1.27.2 (build 133).

I've updated to this version just now, and the icon got reset from the old BoltAI one (yellow) to Default (white).

Running macOS Sequoia 15.1.

**Comment by edigaryev** [comment]
Just got the app's icon reverted again on the newest v1.27.3 (build 124).

@longseespace could this issue be reopened?
